local ADDON, NS = ...
local function CreateMinimapButton()
    local btn = CreateFrame("Button", "JamboRotationMinimap", Minimap)
    btn:SetSize(32, 32)
    btn:SetFrameStrata("MEDIUM")
    btn:SetFrameLevel(8)
    btn:SetPoint("CENTER", -20, -80)
    btn:SetNormalTexture("Interface\\Icons\\Ability_Repair")
    btn:GetNormalTexture():SetTexCoord(0.1, 0.9, 0.1, 0.9)
    local border = btn:CreateTexture(nil, "OVERLAY")
    border:SetTexture("Interface\\Minimap\\MiniMap-TrackingBorder")
    border:SetSize(54, 54)
    border:SetPoint("TOPLEFT", 0, 0)
    btn:SetMovable(true)
    btn:RegisterForDrag("LeftButton")
    btn:SetScript("OnDragStart", function(self)
        self:SetScript("OnUpdate", function()
            local x,y = GetCursorPosition()
            local s = Minimap:GetEffectiveScale()
            local mx,my = Minimap:GetCenter()
            local a = math.atan2((y/s)-my, (x/s)-mx)
            self:SetPoint("CENTER", Minimap, "CENTER", 80*math.cos(a), 80*math.sin(a))
        end)
    end)
    btn:SetScript("OnDragStop", function(self) self:SetScript("OnUpdate", nil) end)
    btn:SetScript("OnClick", function() NS.UI:Toggle() end)
end
local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent", CreateMinimapButton)
SLASH_JAMBOROT1 = "/jr"
SlashCmdList["JAMBOROT"] = function() NS.UI:Toggle() end