-- Jambo Gear - Multi-class gear set management addon
-- Author: Generated by Copilot

-- Ensure we have NUM_BAG_SLOTS defined
if not NUM_BAG_SLOTS then NUM_BAG_SLOTS = 4 end

-- Always use our own LibStub implementation to avoid conflicts
local JamboGearLibStub = function(name, silent)
    if name == "AceAddon-3.0" then
        return {
            NewAddon = function(self, addonName, ...)
                local addon = {
                    name = addonName,
                    modules = {},
                    orderedModules = {},
                    defaultModuleState = true,
                    enabledState = true,
                    dependencies = {...},
                    
                    -- Core methods that AceAddon provides
                    RegisterChatCommand = function() end,
                    RegisterEvent = function(self, event, method)
                        if not self.events then self.events = {} end
                        self.events[event] = method or event
                        if method and type(method) == "string" and self[method] then
                            self.frame = self.frame or CreateFrame("Frame")
                            self.frame:RegisterEvent(event)
                            self.frame:SetScript("OnEvent", function(frame, event, ...)
                                if self[method] then self[method](self, ...) end
                            end)
                        end
                    end,
                    UnregisterEvent = function(self, event)
                        if self.frame then
                            self.frame:UnregisterEvent(event)
                        end
                    end,
                    UnregisterAllEvents = function(self)
                        if self.frame then
                            self.frame:UnregisterAllEvents()
                        end
                    end,
                    Print = function(self, msg)
                        if msg then
                            print("|cff00ff00" .. (self.name or "JamboGear") .. ":|r " .. tostring(msg))
                        end
                    end,
                    Printf = function(self, fmt, ...)
                        self:Print(string.format(fmt, ...))
                    end,
                    
                    -- Module system stubs
                    NewModule = function(self, name)
                        local module = {name = name, Print = self.Print}
                        self.modules[name] = module
                        return module
                    end,
                    GetModule = function(self, name)
                        return self.modules[name]
                    end,
                    
                    -- State management
                    Enable = function(self)
                        if not self.enabledState then
                            self.enabledState = true
                            if self.OnEnable then self:OnEnable() end
                        end
                    end,
                    Disable = function(self)
                        if self.enabledState then
                            self.enabledState = false  
                            if self.OnDisable then self:OnDisable() end
                        end
                    end,
                    IsEnabled = function(self)
                        return self.enabledState
                    end
                }
                _G[addonName] = addon
                
                -- Queue for initialization
                local frame = CreateFrame("Frame")
                frame:RegisterEvent("ADDON_LOADED")
                frame:RegisterEvent("PLAYER_LOGIN")
                frame:SetScript("OnEvent", function(f, event, loadedAddon)
                    if event == "ADDON_LOADED" and loadedAddon == addonName then
                        if addon.OnInitialize then
                            addon:OnInitialize()
                        end
                        f:UnregisterEvent("ADDON_LOADED")
                    elseif event == "PLAYER_LOGIN" then
                        if addon.OnEnable then
                            addon:OnEnable()
                        end
                        f:UnregisterEvent("PLAYER_LOGIN")
                    end
                end)
                
                return addon
            end
        }
    elseif name == "AceDB-3.0" then
        return {
            New = function(self, name, defaults)
                _G[name] = _G[name] or {}
                local db = { profile = _G[name] }
                -- Set defaults
                if defaults and defaults.profile then
                    for k, v in pairs(defaults.profile) do
                        if db.profile[k] == nil then
                            db.profile[k] = v
                        end
                    end
                end
                return db
            end
        }
    end
    if not silent then
        print("LibStub: Library " .. name .. " not found, using fallback")
    end
    return {}
end

-- Store the original LibStub if it exists
local originalLibStub = LibStub

-- Create our AceAddon implementation (so we can register it with any existing LibStub)
local aceAddonImpl = JamboGearLibStub("AceAddon-3.0")

-- If there is an existing LibStub library manager, register our AceAddon implementation so other addons can retrieve it
if originalLibStub and type(originalLibStub.NewLibrary) == "function" then
    local ok, registered = pcall(function() return originalLibStub:NewLibrary("AceAddon-3.0", 13) end)
    if ok and registered then
        -- Copy our implementation into the registered library table
        for k, v in pairs(aceAddonImpl) do
            registered[k] = v
        end
    end
else
    -- There's no existing LibStub; publish our own as the global LibStub fallback
    LibStub = JamboGearLibStub
end

JamboGear = LibStub("AceAddon-3.0"):NewAddon("JamboGear")

local JG = JamboGear

-- Ensure Print method exists
if not JG.Print then
    JG.Print = function(self, msg)
        if msg then
            print("|cff00ff00JamboGear:|r " .. tostring(msg))
        end
    end
end

-- Default configuration
JG.defaults = {
    profile = {
        enabled = true,
        autoSwap = true,
        autoEquipOnLoot = false,
        automationMode = "None", -- NEW: Replaces the boolean check
        showMessages = true,
        showOverlays = true,
        gearSets = {},
        priorities = {},
        weights = {}, -- NEW: Custom Stat Weights storage
        classConfigs = {},
        cachedBank = {} 
    }
}

-- Class specifications mapping
JG.ClassSpecs = {
    WARRIOR = {
        { name = "Arms", role = "DPS" },
        { name = "Fury", role = "DPS" },
        { name = "Protection", role = "Tank" }
    },
    PALADIN = {
        { name = "Holy", role = "Healer" },
        { name = "Protection", role = "Tank" },
        { name = "Retribution", role = "DPS" }
    },
    HUNTER = {
        { name = "Beast Mastery", role = "DPS" },
        { name = "Marksmanship", role = "DPS" },
        { name = "Survival", role = "DPS" }
    },
    ROGUE = {
        { name = "Assassination", role = "DPS" },
        { name = "Combat", role = "DPS" },
        { name = "Subtlety", role = "DPS" }
    },
    PRIEST = {
        { name = "Discipline", role = "Healer" },
        { name = "Holy", role = "Healer" },
        { name = "Shadow", role = "DPS" }
    },
    SHAMAN = {
        { name = "Elemental", role = "DPS" },
        { name = "Enhancement", role = "DPS" },
        { name = "Restoration", role = "Healer" }
    },
    MAGE = {
        { name = "Arcane", role = "DPS" },
        { name = "Fire", role = "DPS" },
        { name = "Frost", role = "DPS" }
    },
    WARLOCK = {
        { name = "Affliction", role = "DPS" },
        { name = "Demonology", role = "DPS" },
        { name = "Destruction", role = "DPS" }
    },
    DRUID = {
        { name = "Balance", role = "DPS" },
        { name = "Feral", role = "DPS" },
        { name = "Guardian", role = "Tank" },
        { name = "Restoration", role = "Healer" }
    }
}

-- Equipment slots
JG.Slots = {
    { id = 1, name = "Head", key = "HeadSlot" },
    { id = 2, name = "Neck", key = "NeckSlot" },
    { id = 3, name = "Shoulder", key = "ShoulderSlot" },
    { id = 5, name = "Chest", key = "ChestSlot" },
    { id = 6, name = "Waist", key = "WaistSlot" },
    { id = 7, name = "Legs", key = "LegsSlot" },
    { id = 8, name = "Feet", key = "FeetSlot" },
    { id = 9, name = "Wrist", key = "WristSlot" },
    { id = 10, name = "Hands", key = "HandsSlot" },
    { id = 11, name = "Finger0", key = "Finger0Slot" },
    { id = 12, name = "Finger1", key = "Finger1Slot" },
    { id = 13, name = "Trinket0", key = "Trinket0Slot" },
    { id = 14, name = "Trinket1", key = "Trinket1Slot" },
    { id = 15, name = "Back", key = "BackSlot" },
    { id = 16, name = "MainHand", key = "MainHandSlot" },
    { id = 17, name = "SecondaryHand", key = "SecondaryHandSlot" },
    { id = 18, name = "Ranged", key = "RangedSlot" }
}

-- Gear slot priorities for different roles
JG.RoleStatPriorities = {
    Tank = {
        primary = {"Armor", "Stamina", "Defense", "Block", "Dodge", "Parry"},
        secondary = {"Strength", "Agility"},
        tertiary = {"Hit", "Crit"}
    },
    Healer = {
        primary = {"Intellect", "Spirit", "SpellPower", "MP5"},
        secondary = {"Stamina"},
        tertiary = {"SpellCrit", "SpellHit"}
    },
    DPS = {
        primary = {"AttackPower", "Strength", "Agility", "Intellect"},
        secondary = {"Hit", "Crit", "Haste"},
        tertiary = {"Stamina", "Spirit"}
    }
}

function JG:OnInitialize()
    -- Initialize the database
    if LibStub and LibStub("AceDB-3.0", true) then
        self.db = LibStub("AceDB-3.0"):New("JamboGearDB", self.defaults, true)
    else
        -- Simple fallback database
        _G.JamboGearDB = _G.JamboGearDB or {}
        self.db = { profile = _G.JamboGearDB }
        
        -- Initialize defaults
        for k, v in pairs(self.defaults.profile) do
            if self.db.profile[k] == nil then
                self.db.profile[k] = v
            end
        end
    end
    
    -- Get player info
    self.playerName = UnitName("player")
    self.playerClass = select(2, UnitClass("player"))
    
    -- Initialize class configuration
    self:InitializeClassConfig()
    
    -- Register chat command
    SLASH_JAMBOGEAR1 = "/jambogear"
    SLASH_JAMBOGEAR2 = "/jg"
    SlashCmdList["JAMBOGEAR"] = function(msg) 
        if JG and JG.ChatCommand then
            JG:ChatCommand(msg) 
        else
            print("ERROR: JamboGear ChatCommand not found")
        end
    end
    
    -- Also register a simple test command
    SLASH_JGTEST1 = "/jgtest"
    SlashCmdList["JGTEST"] = function(msg)
        print("JamboGear test command working!")
        if JG then
            JG:Print("JamboGear object exists")
        else
            print("ERROR: JG object not found")
        end
    end
    
    self:Print("Jambo Gear loaded! Use /jg to open configuration. Test with /jgtest")
end

function JG:OnEnable()
    -- Register events
    local frame = CreateFrame("Frame")
    frame:RegisterEvent("PLAYER_ENTERING_WORLD")
    frame:RegisterEvent("PLAYER_TALENT_UPDATE")
    frame:RegisterEvent("PLAYER_SPECIALIZATION_CHANGED")
    frame:RegisterEvent("PLAYER_REGEN_ENABLED") -- Left combat
    frame:RegisterEvent("BAG_UPDATE")
    frame:RegisterEvent("UNIT_INVENTORY_CHANGED")
    frame:RegisterEvent("ADDON_LOADED")
    frame:SetScript("OnEvent", function(self, event, ...)
        if event == "ADDON_LOADED" then
            local addonName = ...
            if addonName == "Baganator" then
                JG:HookBaganator()
            end
        elseif JG[event] then
            JG[event](JG, event, ...)
        end
    end)
    self.eventFrame = frame
    
    self:Print("Jambo Gear is ready! Independent gear management system loaded.")
    -- Hook tooltips to show enhanced scores
    if not self._tooltipHooked then
        local function HookTip(tooltip)
            tooltip:HookScript("OnTooltipSetItem", function(tt)
                local _, link = tt:GetItem()
                if link then JG:AnnotateTooltip(tt, link) end
            end)
            tooltip:HookScript("OnTooltipCleared", function(tt)
                tt.jgAnnotatedItem = nil
            end)
        end

        -- Standard Tooltips
        if GameTooltip then HookTip(GameTooltip) end
        if ItemRefTooltip then HookTip(ItemRefTooltip) end
        
        -- Comparison/Shopping Tooltips (Shift-Hover)
        if ShoppingTooltip1 then HookTip(ShoppingTooltip1) end
        if ShoppingTooltip2 then HookTip(ShoppingTooltip2) end
        
        self._tooltipHooked = true
    end

    -- Hook container frame item button load to create overlays
    if ContainerFrameItemButtonMixin and not self._bagOverlayHooked then
        hooksecurefunc(ContainerFrameItemButtonMixin, "OnLoad", function(button)
            if not button then return end
            JG:CreateButtonOverlay(button)
        end)
        -- Hook global ContainerFrame_Update to refresh overlays
        hooksecurefunc("ContainerFrame_Update", function(frame)
            JG:UpdateContainerFrameOverlays(frame)
        end)
        self._bagOverlayHooked = true
    end
    -- Refresh overlays immediately
    if self.UpdateAllContainerFrameOverlays then
        self:UpdateAllContainerFrameOverlays()
    end
end

function JG:HookBaganator()
    if not Baganator then return end
    -- Hook Baganator item button mixins
    if BaganatorClassicCachedItemButtonMixin then
        hooksecurefunc(BaganatorClassicCachedItemButtonMixin, "OnLoad", function(self)
            JG:CreateButtonOverlay(self)
        end)
    end
    if BaganatorClassicLiveContainerItemButtonMixin then
        hooksecurefunc(BaganatorClassicLiveContainerItemButtonMixin, "MyOnLoad", function(self)
            JG:CreateButtonOverlay(self)
        end)
    end
    if BaganatorClassicLiveGuildItemButtonMixin then
        hooksecurefunc(BaganatorClassicLiveGuildItemButtonMixin, "OnLoad", function(self)
            JG:CreateButtonOverlay(self)
        end)
    end
    -- For live container, it inherits ContainerFrameItemButtonTemplate, so overlays are already created by UpdateBags
    -- For cached and guild, we create overlays on load
    -- To update, we can hook the update functions or just update on BAG_UPDATE
    self:Print("Baganator support enabled.")
end

function JG:PLAYER_TALENT_UPDATE()
    self:CheckAndEquipSetForRoleChange()
end

function JG:PLAYER_SPECIALIZATION_CHANGED()
    self:CheckAndEquipSetForRoleChange()
end

function JG:CheckAndEquipSetForRoleChange()
    local newSpec = nil
    if self.GetDefaultSpec then newSpec = self:GetDefaultSpec() end
    if not newSpec then
        -- Fallback: choose the first DPS spec or first spec for the class
        local classSpecs = self.ClassSpecs[self.playerClass] or {}
        for _, s in ipairs(classSpecs) do
            if s.role == "DPS" then newSpec = s.name; break end
        end
        if not newSpec and classSpecs[1] then newSpec = classSpecs[1].name end
    end
    if not newSpec then return end
    local newRole = self:GetSpecRole(newSpec)
    if newRole == self.lastKnownRole then return end
    self.lastKnownRole = newRole
    -- Find any set matching this role
    local classConfig = self:GetCurrentClassConfig()
    if not classConfig or not classConfig.gearSets then return end
    if not self.db.profile.autoEquipOnRoleChange then return end
    for setName, gearSet in pairs(classConfig.gearSets) do
        local setRole = (gearSet.meta and gearSet.meta.role) or self:GetSpecRole(setName)
        if setRole == newRole then
            self:SwapToOptimalGear(setName)
            return
        end
    end
end

-- Create overlay on a bag/equip button if it doesn't already exist
-- Create overlay on a bag/equip button if it doesn't already exist
function JG:CreateButtonOverlay(button)
    if not button then return end
    if button.JGSpecOverlay then return end
    
    local overlay = CreateFrame("Frame", nil, button)
    overlay:SetSize(16, 16)
    overlay:SetPoint("TOPLEFT", button, "TOPLEFT", 2, -2)
    
    overlay.texture = overlay:CreateTexture(nil, "BORDER")
    overlay.texture:SetAllPoints(overlay)
    
    overlay.icon = overlay:CreateTexture(nil, "OVERLAY")
    overlay.icon:SetAllPoints(overlay)
    
    overlay.text = overlay:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
    overlay.text:SetAllPoints(overlay)
    overlay.text:SetJustifyH("CENTER")
    overlay.text:SetJustifyV("MIDDLE") -- FIXED: Changed from "CENTER" to "MIDDLE"
    
    overlay:Hide()
    button.JGSpecOverlay = overlay
end

-- Update overlay for a single bag button (show/hide and set to D/T/H)
function JG:UpdateOverlayForButton(button)
    if not button or not button.JGSpecOverlay then return end
    local overlay = button.JGSpecOverlay
    if not self.db or not self.db.profile or not self.db.profile.showOverlays then overlay:Hide(); return end
    -- Determine item link from container button
    local bagFrame = button:GetParent()
    local bagID = nil
    if bagFrame and bagFrame.GetID then
        bagID = bagFrame:GetID()
        if bagID then bagID = bagID - 1 end
    end
    local slotID = button:GetID()
    local link = nil
    if bagID and slotID and bagID >= 0 then
        link = GetContainerItemLink(bagID, slotID)
    end
    if not link then
        overlay:Hide()
        return
    end
    -- Compute best spec for this item
    local itemInfo = self:GetItemInfo(link)
    if not itemInfo then overlay:Hide(); return end
    local classConfig = self:GetCurrentClassConfig()
    if not classConfig or not classConfig.specPriority then overlay:Hide(); return end
    local bestSpec, bestScore = nil, -math.huge
    for _, specData in ipairs(classConfig.specPriority) do
        if specData.enabled then
            local score = self:GetEnhancedItemScore(itemInfo, specData.name) or 0
            if score > bestScore then
                bestScore = score
                bestSpec = specData
            end
        end
    end
    if not bestSpec then overlay:Hide(); return end
    -- Use role to determine icon
    local role = bestSpec.role or self:GetSpecRole(bestSpec.name)
    local text = "?"
    local r,g,b = 1,1,1
    if role == "DPS" then text = "D"; r,g,b = 1,0,0
    elseif role == "Tank" then text = "T"; r,g,b = 0.2,0.6,1
    elseif role == "Healer" then text = "H"; r,g,b = 0.2,1,0.2
    end
    overlay.texture:Hide()
    local iconPaths = {
        DPS = "Interface\\Icons\\INV_Sword_27",
        Tank = "Interface\\Icons\\INV_Shield_06",
        Healer = "Interface\\Icons\\Spell_Holy_Heal"
    }
    -- Determine if item is in any set
    local function getItemID(link)
        if not link then return nil end
        return link:match("item:(%d+)")
    end
    local itemID = getItemID(link)
    local inAnySet = false
    for setName, gearSet in pairs(classConfig.gearSets or {}) do
        for slotName, gearItem in pairs(gearSet) do
            if gearItem and gearItem.link then
                local gid = getItemID(gearItem.link)
                if gid and itemID and gid == itemID then
                    inAnySet = true
                    break
                end
            end
        end
        if inAnySet then break end
    end

    local iconPath = iconPaths[role]
    if not inAnySet then
        iconPath = "Interface\\Icons\\INV_Misc_Trash_01"
    end
    if iconPath then
        overlay.icon:SetTexture(iconPath)
        overlay.icon:Show()
        overlay.text:SetText("")
    else
        overlay.icon:Hide()
        overlay.texture:SetColorTexture(r, g, b, 0.75)
        overlay.texture:Show()
        overlay.text:SetText(text)
    end
    overlay:Show()
end

-- Update overlays for every item button in a container frame
function JG:UpdateContainerFrameOverlays(frame)
    if not frame then return end
    local name = frame:GetName()
    if not name then return end
    local maxSlots = 36
    for i = 1, maxSlots do
        local button = _G[name .. "Item" .. i]
        if button and button.JGSpecOverlay then
            JG:UpdateOverlayForButton(button)
        elseif button then
            -- Create overlay if not exists
            JG:CreateButtonOverlay(button)
            JG:UpdateOverlayForButton(button)
        end
    end
end

function JG:InitializeClassConfig()
    local class = self.playerClass
    
    if not self.db.profile.classConfigs[class] then
        self.db.profile.classConfigs[class] = {
            specPriority = {},
            gearSets = {},
            autoEquipOnRoleChange = true
        }
        
        -- Set default spec priorities based on class
        local specs = self.ClassSpecs[class]
        if specs then
            for i, spec in ipairs(specs) do
                self.db.profile.classConfigs[class].specPriority[i] = {
                    name = spec.name,
                    role = spec.role,
                    priority = i,
                    enabled = true
                }
            end
        end
    end
    -- Create a default DPS set for the class if none exists
    local configs = self.db.profile.classConfigs[class]
    local hasSet = false
    for k, _ in pairs(configs.gearSets or {}) do hasSet = true; break end
    if not hasSet then
        -- Find a DPS spec
        local dpsSpec = nil
        for _, s in ipairs(self.ClassSpecs[class] or {}) do
            if s.role == "DPS" then
                dpsSpec = s.name
                break
            end
        end
        if dpsSpec then
            configs.gearSets[dpsSpec] = { meta = { role = "DPS", assignedSpec = dpsSpec } }
        end
    end
end

function JG:GetCurrentClassConfig()
    return self.db.profile.classConfigs[self.playerClass]
end

function JG:ChatCommand(input)
    -- Check if input is empty or just whitespace
    if not input or input == "" or input:match("^%s*$") then
        if self.ToggleGUI then
            self:ToggleGUI()
        else
            self:Print("UI module not loaded.")
        end
        return
    end
    
    local command, args = input:match("^(%S+)%s*(.*)")
    if command then
        command = command:lower()
        if command == "config" or command == "gui" then
            if self.ToggleGUI then self:ToggleGUI() end
        elseif command == "swap" then
            self:SwapToOptimalGear(args)
        elseif command == "scan" then
            self:ScanAndUpdateGear()
            self:Print("Gear scanned.")
        elseif command == "debug" then
            self.db.profile.debugMode = not self.db.profile.debugMode
            self:Print("Debug mode " .. (self.db.profile.debugMode and "enabled" or "disabled") .. ".")
        elseif command == "enable" then
            self.db.profile.enabled = true
            self:Print("Enabled.")
        elseif command == "disable" then
            self.db.profile.enabled = false
            self:Print("Disabled.")
        else
            self:Print("Unknown command. Try: /jg swap [spec]")
        end
    end
end

function JG:PLAYER_ENTERING_WORLD()
    -- Delay to ensure all addons are loaded
    local function delayedScan()
        self:ScanAndUpdateGear()
    end
    
    if C_Timer and C_Timer.After then
        C_Timer.After(2, delayedScan)
    else
        -- Fallback for older versions
        local timer = 0
        local frame = CreateFrame("Frame")
        frame:SetScript("OnUpdate", function(self, elapsed)
            timer = timer + elapsed
            if timer >= 2 then
                delayedScan()
                frame:SetScript("OnUpdate", nil)
            end
        end)
    end
end

function JG:PLAYER_REGEN_ENABLED()
    -- Auto-swap gear after combat if enabled
    if self.db.profile.autoSwap and self.pendingGearSwap then
        self:SwapToOptimalGear()
        self.pendingGearSwap = nil
    end
end

function JG:BAG_UPDATE()
    -- Delay gear scanning to avoid spam
    if not self.scanTimer then
        local function delayedScan()
            self:ScanAndUpdateGear()
            self.scanTimer = nil
            
            -- AUTO EQUIP LOGIC
            if self.db.profile.autoEquipOnLoot and not InCombatLockdown() then
                -- Determine Role (Default to DPS if nil)
                -- We look at the currently active set or the player's last known role
                local currentRole = self.lastKnownRole or "DPS"
                
                -- We need to find a Spec Name that matches this Role
                -- (Since SwapToOptimalGear takes a Spec Name, not a Role)
                local classConfig = self:GetCurrentClassConfig()
                local targetSpec = nil
                
                -- 1. Try to keep current spec if it matches role
                local currentSpec = self:GetDefaultSpec()
                if currentSpec and self:GetSpecRole(currentSpec) == currentRole then
                    targetSpec = currentSpec
                end
                
                -- 2. If not, find the highest priority spec for this role
                if not targetSpec and classConfig and classConfig.specPriority then
                     for _, s in ipairs(classConfig.specPriority) do
                        if s.role == currentRole and s.enabled then
                            targetSpec = s.name
                            break
                        end
                     end
                end
                
                -- 3. Fallback: Just find any spec with this role
                if not targetSpec then
                    local specs = self.ClassSpecs[self.playerClass] or {}
                    for _, s in ipairs(specs) do
                        if s.role == currentRole then targetSpec = s.name; break end
                    end
                end
                
                if targetSpec then
                    self:SwapToOptimalGear(targetSpec)
                end
            end
        end
        
        if C_Timer and C_Timer.After then
            self.scanTimer = C_Timer.After(1, delayedScan)
        end
    end
end

-- Update every open container frame's overlays
function JG:UpdateAllContainerFrameOverlays()
    local maxFrames = 12
    for i = 1, maxFrames do
        local frame = _G["ContainerFrame"..i]
        if frame and frame:IsShown() then
            self:UpdateContainerFrameOverlays(frame)
        end
    end
    if ContainerFrameCombinedBags and ContainerFrameCombinedBags:IsVisible() then
        self:UpdateContainerFrameOverlays(ContainerFrameCombinedBags)
    end
end

function JG:UNIT_INVENTORY_CHANGED(event, unit)
    if unit == "player" then
        self:BAG_UPDATE()
    end
end

-- Initialize the addon
local initFrame = CreateFrame("Frame")
initFrame:RegisterEvent("ADDON_LOADED")
initFrame:SetScript("OnEvent", function(self, event, addonName)
    if addonName == "Jambo_Gear" then
        JG:OnInitialize()
        JG:OnEnable()
        self:UnregisterEvent("ADDON_LOADED")
    end
end)

function JG:GetDefaultSpec()
    local classConfig = self:GetCurrentClassConfig()
    if not classConfig or not classConfig.specPriority then return nil end
    for _, specData in ipairs(classConfig.specPriority) do
        if specData.enabled then
            return specData.name
        end
    end
    return nil
end